# Generated by Django 6.0.7 on 2026-08-19 12:45

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_path, validators=[accounts.validators.validate_image_file, accounts.validators.validate_avatar_size]),
        ),
    ]
