# Generated by Django 6.0.7 on 2026-08-14 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
