# Generated by Django 6.0.7 on 2026-08-01 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
