# Generated by Django 6.0.7 on 2026-08-07 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('cancelled_early_weight', models.DecimalField(decimal_places=2, default=0.25, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('cancelled_late_weight', models.DecimalField(decimal_places=2, default=0.75, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('no_show_weight', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_pending_appointments', models.PositiveSmallIntegerField(default=3)),
                ('reliability_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
