# Generated by Django 6.0.7 on 2026-08-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconfiguration',
            name='max_advance_booking_days',
            field=models.PositiveIntegerField(default=30, help_text='Maximum number of days in advance that a patient can book an appointment.'),
        ),
    ]
