# Generated by Django 6.0.7 on 2026-08-08 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_clinicconfiguration_max_advance_booking_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliabilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_reliability', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_pending_appointments', models.PositiveIntegerField()),
                ('max_advance_booking_days', models.PositiveIntegerField()),
                ('block_online_booking', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['min_reliability'],
            },
        ),
        migrations.RemoveField(
            model_name='clinicconfiguration',
            name='max_advance_booking_days',
        ),
        migrations.RemoveField(
            model_name='clinicconfiguration',
            name='max_pending_appointments',
        ),
    ]
