# Generated by Django 6.0.7 on 2026-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'Register'), ('email_verified', 'Email Verified'), ('appointment_created', 'Appointment Created'), ('appointment_updated', 'Appointment Updated')], max_length=50),
        ),
    ]
