# Generated by Django 6.0.7 on 2026-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'Register'), ('email_verified', 'Email Verified'), ('email_changed', 'Email Changed'), ('appointment_created', 'Appointment Created'), ('appointment_updated', 'Appointment Updated')], max_length=50),
        ),
    ]
