# Generated by Django 6.0.7 on 2026-07-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('title', models.CharField(blank=True, help_text='e.g., Head of Operations, Billing Supervisor', max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, help_text='e.g., Front Desk, Billing, Human Resources', max_length=100)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
    ]
