# Generated by Django 6.0.7 on 2026-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='checkup_duration',
            field=models.PositiveIntegerField(default=45, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='follow_up_duration',
            field=models.PositiveIntegerField(default=15, help_text='Duration in minutes'),
        ),
    ]
